NinetyNineCats/config/routes.rb
Rails.application.routes.draw do
  resources :cats do
    resources :cat_rental_requests, only: [:index]
  end
  resources :cat_rental_requests, only: [:show, :update, :create, :new, :edit, :destroy]
end

NinetyNineCats/app/models/cat.rb
class Cat < ActiveRecord::Base
  has_many :cat_rental_requests, dependent: :destroy
  COLORS = ['turquoise', 'magenta', 'cyan']
  validates :birth_date, :color, :name, :sex, presence: true
  validates :color, inclusion: { in: COLORS, message: "You must choose OUR colors"}
  validates :sex, inclusion: { in: %w(f m), message: "You must conform to our gender standards"}

  def self.color_options
    COLORS
  end
end

NinetyNineCats/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  belongs_to :cat
  STATUS_OPTIONS = ["PENDING", "APPROVED", "DENIED"]
  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: STATUS_OPTIONS, message: "Invalid Status"}
  validate :no_overlapping_rentals

  def self.status_options
    STATUS_OPTIONS
  end

  def overlapping_requests
    if id
      rentals_on_my_cat = CatRentalRequest.where("cat_id = ? AND id != ?", cat_id, id)
    else
      rentals_on_my_cat = CatRentalRequest.where(cat_id: cat_id)
    end
    not_overlapping = rentals_on_my_cat.where("(start_date < ? AND end_date < ?) OR (start_date > ? AND end_date > ?)", start_date, end_date, start_date, end_date)
    rentals_on_my_cat.where('id NOT IN (?)', not_overlapping.select(id) )
  end

  def overlapping_approved_requests
    overlapping_requests.where(status: "APPROVED")
  end

  def no_overlapping_rentals
    unless overlapping_approved_requests.empty? || status != "APPROVED"
      errors[:start_date] << "Rentals can't overlap!"
    end
  end

  def approve!
    CatRentalRequest.transaction do
      if overlapping_approved_requests.empty?
        self.update(status: "APPROVED")
        overlapping_requests.update_all(status: "DENIED")
      end
    end
  end

  def deny!
    self.update(status: "DENIED")
  end

end

NinetyNineCats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

NinetyNineCats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def index
    @cat = Cat.find_by(id: params[:cat_id])
    @rentals = @cat.cat_rental_requests
  end

  def new
    @cats = Cat.all
    @cat_rental_request = CatRentalRequest.new
  end

  def create
    @cats = Cat.all
    @cat_rental_request = CatRentalRequest.new(rental_params)

    @cat_rental_request.status = "APPROVED"
    if @cat_rental_request.save
      redirect_to cat_url(Cat.find_by(id: @cat_rental_request.cat_id)) + '/cat_rental_requests'
    else
      render :new
    end
  end

  def update
    if params[:stuff] == "approve!"
      @cat_rental_request = CatRentalRequest.find_by(id: params[:id])
      @cat_rental_request.approve!
      redirect_to cat_url(@cat_rental_request.cat)
    else
      @cat_rental_request = CatRentalRequest.find_by(id: params[:id])
      @cat_rental_request.deny!
      redirect_to cat_url(@cat_rental_request.cat)
    end
  end


  def rental_params
    params[:cat_rental_request].permit(:cat_id, :start_date, :end_date)
  end
end

NinetyNineCats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find_by(id: params[:id])
  end

  def new
    @cat = Cat.new()
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
  end

  def update
    @cat = Cat.find_by(id: params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  def destroy
    @cat = Cat.find_by(id: params[:id])
    if @cat.destroy
      redirect_to cats_url
    else
      render json: "You can't destroy this"
    end
  end

  private
  def cat_params
    params[:cat].permit(:birth_date, :color, :name, :sex, :description)
  end
end

NinetyNineCats/app/helpers/application_helper.rb
module ApplicationHelper
end

NinetyNineCats/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

NinetyNineCats/app/helpers/cats_helper.rb
module CatsHelper
end

NinetyNineCats/app/views/cat_rental_requests/_form.html.erb
<form action = <%= my_action %> method="Post" >
  <input type='hidden' name="_method" value=<%= my_method %>>

  <label>Cat</label>
  <select name="cat_rental_request[cat_id]">
    <% @cats.each do |cat| %>
    <option value=<%= cat.id %> <%= 'selected' if cat.id == @cat_rental_request.cat_id%> > <%= cat.name %></option>
    <% end %>
  </select>
  <br>

  <label>Start Date</label>
  <input type="date" name="cat_rental_request[start_date]" value=<%= @cat_rental_request.start_date %>>
  <br>

  <label>End Date</label>
  <input type="date" name="cat_rental_request[end_date]" value=<%= @cat_rental_request.end_date %>>
  <br>

  <input type="submit" value=" <%= submit_name %> ">
</form>

NinetyNineCats/app/views/cat_rental_requests/index.html.erb
<h3>Rentals for <%= @cat.name %></h3>

<table>
  <tr>
    <% @rentals.first.attributes.each do |variable, value| %>
      <th> <%= variable %> </th>
    <% end %>
  </tr>
  
  <% @rentals.each do |rental| %>

  <tr>
    <% rental.attributes.each do |variable, value| %>
      <th> <%= value %> </th>
    <% end %>
  </tr>
  <% end %>
</table>

NinetyNineCats/app/views/cat_rental_requests/new.html.erb
<h3>New Rental Request</h3>


<%= render partial: "form", locals: {submit_name: 'Send Request', my_action: '/cat_rental_requests', my_method: 'Post'} %>

NinetyNineCats/app/views/cats/_form.html.erb
<form action = <%= my_action %> method="Post" >
  <input type='hidden' name="_method" value=<%= my_method %>>

  <label>Name</label>
  <input type="text" name="cat[name]" value=<%= @cat.name %>>
  <br>

  <label>Birth Date</label>
  <input type="date" name="cat[birth_date]" value=<%= @cat.birth_date %>>
  <br>

  <label>Color</label>
  <select name="cat[color]">
    <% Cat.color_options.each do |color| %>
    <option value=<%= color %> <%= 'selected' if color == @cat.color%> > <%= color.upcase %></option>
    <% end %>
  </select>
  <br>

  <label>Sex</label>
  <select name="cat[sex]">
    <% ['f', 'm'].each do |sex| %>
    <option value=<%= sex %> <%= 'selected' if sex == @cat.sex%>> <%= sex.upcase %> </option>
    <% end %>
  </select>
  <br>

  <label>Description</label>
  <textarea name="cat[description]" ><%= @cat.description %></textarea>
  <br>

  <input type="submit" value=" <%= submit_name %> ">
</form>

NinetyNineCats/app/views/cats/edit.html.erb
<h3>Edit Cat <%= @cat.name %><h3>

<%= render partial: "form", locals: {submit_name: 'Update Cat',
  my_action: cat_url(@cat), my_method: 'Patch'} %>

NinetyNineCats/app/views/cats/index.html.erb
<h3>Cats</h3>

<ul>
<% @cats.each do |cat| %>
  <li> <a href=' <%= cat_url(cat) %> ' ><%= cat.name %> </a></li>
<% end %>
</ul>

<a href=' <%= new_cat_url %> ' > Create New Cat </a>

NinetyNineCats/app/views/cats/new.html.erb
<h3>New Cat<h3>

<%= render partial: "form", locals: {submit_name: 'Create Cat', my_action: '/cats', my_method: 'Post'} %>

NinetyNineCats/app/views/cats/show.html.erb
<h3> <%= @cat.name %> </h3>
<br>
<a href=' <%= edit_cat_url %> ' > Edit Cat </a>
<%= button_to "delete", @cat, action: :destroy, method: :delete %>
<br>
<table>
  <tr>
    <% @cat.attributes.each do |variable, value| %>
      <th> <%= variable %> </th>
    <% end %>
  </tr>

  <tr>
    <% @cat.attributes.each do |variable, value| %>
      <th> <%= value %> </th>
    <% end %>
  </tr>
</table>

<h3>Rentals for <%= @cat.name %></h3>

<table>
  <tr>
      <th>Start Date</th>
      <th>End Date</th>
  </tr>

  <% @cat.cat_rental_requests.order(:start_date).each do |rental| %>

  <tr>
    <td> <%= rental.start_date %></td>
    <td> <%= rental.end_date %></td>
    <td> <%= rental.status %></td>
    <% if rental.status == "PENDING" %>
      <td> <%= button_to "approve", rental, params: {stuff: "approve!"}, method: :patch %> </td>
      <td> <%= button_to "deny", rental, params: {stuff: "deny!"}, method: :patch %> </td>
    <% end %>
  </tr>
  <% end %>
</table>

NinetyNineCats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNineCats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>